// vue/experienced/src/components/HistoryItem.vue
<script lang="ts">

export default {
    props: {
        orderId: String,
        name: String,
        purchaseDate: String,
        total: Number,
        imageUrl: String,
    },
    methods: {
        navigateToOrder() {
            this.$router.push(`/orders/${this.orderId}`)
        }
    }
}


</script>

<template>
    <div class="outer-item-container">
        <div class="item-container">
            <div class="item-info">
                <img class="product-image-history" :src=imageUrl alt="bag" />
                <div class="title-and-price-container">
                    <p>Order #{{ orderId }}</p>
                    <p class="product-price">{{ purchaseDate }}</p>
                </div>
            </div>
            <div class="price-order-container">
                <h3>$ {{ total }} USD</h3>
                <button @click="navigateToOrder">View Order</button>
            </div>
        </div>

    </div>
</template>

// angular/inexperienced/webshop/src/app/history/history-item/history-item.component.ts
import { Component, Input, OnInit } from "@angular/core";
import RegisterInterface from "src/types/RegisterInterface";
import { AbstractControl, FormControl, FormGroup, ValidationErrors, ValidatorFn, Validators } from "@angular/forms";

@Component({
  selector: "app-history-item",
  templateUrl: "./history-item.component.html",
  styleUrls: ["./history-item.component.css"],
})
export class HistoryItemComponent {

  @Input() id: string;
  @Input() date: Date
  @Input() price: number;
  @Input() image_url: string;

  dateFormatOptions = {
    weekday: 'long',
    year: 'numeric',
    month: 'long',
    day: 'numeric'
  } as any;
}

<div class="item-container">
    <div class="item-info">
        <img class="product-image" src={{image_url}} alt="bag" />
        <div class="title-and-price-container">
            <p>Order #{{id}}</p>
            <p class="product-price">{{date.toLocaleDateString('de-DE', dateFormatOptions)}}</p>
        </div>
    </div>
    <div class="price-order-container">
        <h3>$ {{price}} USD</h3>
        <button routerLink="/history/{{id}}">View Order</button>
    </div>
</div>
