// angular/experienced/src/app/register/register.component.ts
import { Component } from '@angular/core';
import { RegisterService, RegisterUser } from '../register.service';
import { CookieService } from '../cookie.service';

@Component({
  selector: 'app-register',
  templateUrl: './register.component.html',
  styleUrls: ['./register.component.css'],
  providers: [RegisterService],
})
export class RegisterComponent {
  user: RegisterUser = {
    email: '',
    username: '',
    password: '',
    password_repeat: '',
  };

  constructor(
    private registerService: RegisterService,
    private cookieService: CookieService
  ) {}

  isLoggedIn() {
    return this.cookieService.isLoggedIn();
  }

  logoutUser() {
    return this.cookieService.logoutUser();
  }

  registerUser() {
    console.log(this.user);
    if (this.user) {
      if (
        this.user.username &&
        this.user.email &&
        this.user.password &&
        this.user.password_repeat
      ) {
        if (this.user.password === this.user.password_repeat) {
          return this.registerService
            .registerUser(this.user)
            .subscribe((result) => {
              console.log(result);
              if (result && result.length > 0) {
                if (result[0]._id) {
                  return alert('Registered!');
                }
              }
              if (result && result['detail' as any]!) {
                return alert(result['detail' as any]);
              }
              return alert('Error registering you!');
            });
        }
        return alert('Passwords does not match');
      }
      return alert('All fields must be filled out');
    }
    return alert('You must fill in all fields');
  }
}

type OnlyKeys = keyof RegisterUser;

<div class="container">
  <h2>REGISTER</h2>
  <p>Register to leave reviews and comments</p>
  <form #userForm="ngForm" (ngSubmit)="registerUser()">
    <input
      [(ngModel)]="user.username"
      type="text"
      id="username"
      name="username"
      class="form-field"
      placeholder="Your name"
      minlength="3"
      required
    />
    <input
      [(ngModel)]="user.email"
      type="text"
      id="email"
      name="email"
      class="form-field"
      placeholder="Your email"
      minlength="4"
      required
    />
    <input
      [(ngModel)]="user.password"
      type="text"
      id="password"
      name="password"
      class="form-field"
      placeholder="Your password"
      minlength="8"
      type="password"
      required
    />
    <input
      [(ngModel)]="user.password_repeat"
      type="text"
      name="password_repeat"
      id="password_repeat"
      class="form-field"
      minlength="8"
      placeholder="Repeat password"
      type="password"
      required
    />
    <button type="submit" [disabled]="userForm.invalid" class="login-button">
      Register
    </button> 
  </form>
   <div *ngIf="isLoggedIn(); then logout; else login"></div>
    <ng-template #login>
      <button class="login-button" routerLink="/login">
        Log in
      </button>
    </ng-template>
    <ng-template #logout>
      <button
        class="login-button"
        routerLink="/register"
        (click)="logoutUser()"
      >
        Log out
      </button>
    </ng-template>
</div>

// svelte/inexperienced/webshop/src/routes/register/+page.svelte
<script lang="ts">
  import { register } from "../../api/register";
  import "../css/register.css";
  import { form, field } from "svelte-forms";
  import { required } from "svelte-forms/validators";
  import { email, min, matchField } from "svelte-forms/validators";

  const usernameField = field("username", "", [required()]);
  const emailField = field("email", "", [email()]);
  const passwordField = field("password", "", [required()]);
  const passwordRepeatField = field("password_repeat", "", [
    required(),
    min(8),
    matchField(passwordField),
  ]);
  
  const registerForm = form(
    usernameField,
    emailField,
    passwordField,
    passwordRepeatField
  );

  function hasError(
    type: "username" | "password" | "password_repeat",
    value: string,
    repeat?: string
  ): boolean {
    if (!value.length) {
      return false;
    }

    if (type === "username") {
      if (value.length < 5) {
        return true;
      }
    }

    if (type === "password") {
      if (value.length < 8) {
        return true;
      }
    }

    if (type === "password_repeat") {
      if (value !== repeat) {
        return true;
      }
    }

    return false;
  }

  function hasErrorInUsername(): boolean {
    return hasError("username", $usernameField.value);
  }

  function hasErrorInPassword(): boolean {
    return hasError("password", $passwordField.value);
  }

  function hasErrorInRepeatedPassword(): boolean {
    return hasError(
      "password_repeat",
      $passwordField.value,
      $passwordRepeatField.value
    );
  }

  async function onSubmit() {
    const form = {
      username: $usernameField.value,
      email: $emailField.value,
      password: $passwordField.value,
    };

    if (
      hasErrorInPassword() ||
      hasErrorInUsername() ||
      hasErrorInRepeatedPassword() ||
      $registerForm.hasError("email.not_an_email")
    ) {
      return alert("Invalid form! Please try again");
    }

    const response = await register(form);
    console.log(response);
    if (response.status_code === 400) {
      return alert(`ERROR: ${response.detail}`);
    }

    return alert("You have successfully registered your account!");
  }
</script>

<div class="container">
  <h2>REGISTER</h2>
  <p>Register to leave reviews and comments</p>
  <input
    bind:value={$usernameField.value}
    type="text"
    class="form-field"
    placeholder="Your name"
  />
  {#if $registerForm.hasError("username.required") || hasError("username", $usernameField.value)}
    <div class="error">
      Username is required and should be at least 5 characters
    </div>
  {/if}
  <input
    bind:value={$emailField.value}
    type="text"
    class="form-field"
    placeholder="Your email"
  />
  {#if $registerForm.hasError("email.not_an_email")}
    <div class="error">Email is not valid!</div>
  {/if}
  <input
    bind:value={$passwordField.value}
    type="text"
    class="form-field"
    placeholder="Your password"
  />
  {#if $registerForm.hasError("password.required") || hasError("password", $passwordField.value)}
    <div class="error">
      Password is required and should be at least 8 characters!
    </div>
  {/if}
  <input
    bind:value={$passwordRepeatField.value}
    type="text"
    class="form-field"
    placeholder="Repeat password"
  />
  {#if hasError("password_repeat", $passwordField.value, $passwordRepeatField.value)}
    <div class="error">Passwords do not match!</div>
  {/if}
  <button on:click={() => onSubmit()} class="login-button">Login</button>
</div>

<style>
  input {
    outline: none;
  }

  :global(.invalid),
  :global(.error) {
    border: 1px solid red;
  }

  :global(.valid),
  :global(.foo) {
    border: 1px solid green;
  }

  :global(.dirty) {
    border: 1px dashed black;
  }
</style>
