// svelte/inexperienced/webshop/src/routes/register/+page.svelte
<script lang="ts">
  import { register } from "../../api/register";
  import "../css/register.css";
  import { form, field } from "svelte-forms";
  import { required } from "svelte-forms/validators";
  import { email, min, matchField } from "svelte-forms/validators";

  const usernameField = field("username", "", [required()]);
  const emailField = field("email", "", [email()]);
  const passwordField = field("password", "", [required()]);
  const passwordRepeatField = field("password_repeat", "", [
    required(),
    min(8),
    matchField(passwordField),
  ]);
  
  const registerForm = form(
    usernameField,
    emailField,
    passwordField,
    passwordRepeatField
  );

  function hasError(
    type: "username" | "password" | "password_repeat",
    value: string,
    repeat?: string
  ): boolean {
    if (!value.length) {
      return false;
    }

    if (type === "username") {
      if (value.length < 5) {
        return true;
      }
    }

    if (type === "password") {
      if (value.length < 8) {
        return true;
      }
    }

    if (type === "password_repeat") {
      if (value !== repeat) {
        return true;
      }
    }

    return false;
  }

  function hasErrorInUsername(): boolean {
    return hasError("username", $usernameField.value);
  }

  function hasErrorInPassword(): boolean {
    return hasError("password", $passwordField.value);
  }

  function hasErrorInRepeatedPassword(): boolean {
    return hasError(
      "password_repeat",
      $passwordField.value,
      $passwordRepeatField.value
    );
  }

  async function onSubmit() {
    const form = {
      username: $usernameField.value,
      email: $emailField.value,
      password: $passwordField.value,
    };

    if (
      hasErrorInPassword() ||
      hasErrorInUsername() ||
      hasErrorInRepeatedPassword() ||
      $registerForm.hasError("email.not_an_email")
    ) {
      return alert("Invalid form! Please try again");
    }

    const response = await register(form);
    console.log(response);
    if (response.status_code === 400) {
      return alert(`ERROR: ${response.detail}`);
    }

    return alert("You have successfully registered your account!");
  }
</script>

<div class="container">
  <h2>REGISTER</h2>
  <p>Register to leave reviews and comments</p>
  <input
    bind:value={$usernameField.value}
    type="text"
    class="form-field"
    placeholder="Your name"
  />
  {#if $registerForm.hasError("username.required") || hasError("username", $usernameField.value)}
    <div class="error">
      Username is required and should be at least 5 characters
    </div>
  {/if}
  <input
    bind:value={$emailField.value}
    type="text"
    class="form-field"
    placeholder="Your email"
  />
  {#if $registerForm.hasError("email.not_an_email")}
    <div class="error">Email is not valid!</div>
  {/if}
  <input
    bind:value={$passwordField.value}
    type="text"
    class="form-field"
    placeholder="Your password"
  />
  {#if $registerForm.hasError("password.required") || hasError("password", $passwordField.value)}
    <div class="error">
      Password is required and should be at least 8 characters!
    </div>
  {/if}
  <input
    bind:value={$passwordRepeatField.value}
    type="text"
    class="form-field"
    placeholder="Repeat password"
  />
  {#if hasError("password_repeat", $passwordField.value, $passwordRepeatField.value)}
    <div class="error">Passwords do not match!</div>
  {/if}
  <button on:click={() => onSubmit()} class="login-button">Login</button>
</div>

<style>
  input {
    outline: none;
  }

  :global(.invalid),
  :global(.error) {
    border: 1px solid red;
  }

  :global(.valid),
  :global(.foo) {
    border: 1px solid green;
  }

  :global(.dirty) {
    border: 1px dashed black;
  }
</style>

// angular/inexperienced/webshop/src/app/register/register.component.ts
import { Component, OnInit } from "@angular/core";
import RegisterService from "../config/register.service";
import RegisterInterface from "src/types/RegisterInterface";
import { AbstractControl, FormControl, FormGroup, ValidationErrors, ValidatorFn, Validators } from "@angular/forms";

@Component({
  selector: "app-register",
  templateUrl: "./register.component.html",
  styleUrls: ["./register.component.css"],
})
export class RegisterComponent implements OnInit {
  registerForm: FormGroup;

  constructor(private registerService: RegisterService) { }

  passwordRepeatValidator(): ValidatorFn {
    return (control: AbstractControl): ValidationErrors | null => {
      if (Validators.minLength(8)(control) !== null) {
        return { minlength: true };
      }

      if (control.value !== this.registerForm?.value.password) {
        return { notEqual: true };
      }

      return null;
    };
  }

  ngOnInit() {
    this.registerForm = new FormGroup({
      username: new FormControl("", [
        Validators.required,
        Validators.minLength(6),
      ]),
      email: new FormControl("", Validators.email),
      password: new FormControl("", [
        Validators.required,
        Validators.minLength(8),
      ]),
      password_repeat: new FormControl("", Validators.compose([
        Validators.required,
        this.passwordRepeatValidator(),
      ])),
    });
  }

  onSubmit() {
    if (this.registerForm.invalid) {
      return alert("Invalid form!");
    }

    const {
      username,
      email,
      password,
      password_repeat,
    } = this.registerForm.value;

    if (password_repeat !== password) {
      return alert("The passwords does not match!");

    }

    const form: RegisterInterface = {
      username,
      email,
      password,
    };

    this.registerService.register(form).subscribe((response) => {
      if (response.status_code === 400) {
        return alert(response.detail)
      }

      alert("You have successfully been registered!");
    });
  }
}

<form [formGroup]="registerForm" novalidate>
    <div class="container">
        <h2>REGISTER</h2>
        <p>Register to leave reviews and comments</p>

        <input formControlName="username" name="username" type="text" class="form-field" placeholder="Your name"
            required />
        <div *ngIf="registerForm.controls['username'].invalid && (registerForm.controls['username'].dirty || registerForm.controls['username'].touched)"
            class="alert alert-danger">
            Name is required and should be at minimum 6 characters.
        </div>

        <input formControlName="email" name="email" type="text" class="form-field" placeholder="Your email" required />
        <div *ngIf="registerForm.controls['email'].invalid && (registerForm.controls['email'].dirty || registerForm.controls['email'].touched)"
            class="alert alert-danger">
            Email is required and should be a valid e-mail.
        </div>

        <input formControlName="password" name="passowrd" type="password" class="form-field" placeholder="Your password"
            required />
        <div *ngIf="registerForm.controls['password'].invalid && (registerForm.controls['password'].dirty || registerForm.controls['password'].touched)"
            class="alert alert-danger">
            Password should be at minimum 8 characters long.
        </div>

        <input formControlName="password_repeat" name="password_repeat" type="password" class="form-field"
            placeholder="Repeat password" required />



        <div *ngIf="registerForm.controls['password_repeat'].invalid && (registerForm.controls['password_repeat'].dirty || registerForm.controls['password_repeat'].touched)"
            class="alert alert-danger">

            <p *ngIf="!registerForm.controls['password_repeat'].hasError('notEqual')">
                Repeat password should be at minimum 8 characters long.
            </p>

            <p *ngIf="registerForm.controls['password_repeat'].hasError('notEqual')">
                Repeat password must equal password
            </p>
        </div>

        <button (click)="onSubmit()" class="login-button">Register</button>
        <button [routerLink]="'/login'" class="login-button">Or login</button>
    </div>
</form>
