// svelte/inexperienced/webshop/src/routes/history/[id]/history-order-item.svelte
<script lang="ts">
    import type { HistoryItem } from "../../../types/History";

    export let item: HistoryItem;
    export let image: string;
</script>

<div class="item-container">
    <div class="item-info">
        <img class="product-image" src={image} alt="bag" />
        <div class="title-and-price-container">
            <p>{item.name} x{item.quantity}</p>
            <p class="product-price">{item.price} USD</p>
        </div>
    </div>
</div>

<style>
    .item-container {
        display: flex;
        background-color: rgb(235, 230, 230);
        border-radius: 3px;
        justify-content: space-between;
        width: 1000px;
    }

    .item-info {
        display: flex;
    }

    .product-image {
        width: 100px;
        padding: 24px;
    }

    .title-and-price-container {
        align-self: center;
    }
</style>

// vue/experienced/src/components/HistoryOrderItem.vue

<script lang="ts">

export default {
    props: {
        imageUrl: String,
        productName: String,
        price: Number,
        quantity: Number
    }
}
</script>

<template>
    <div class="item-container">
        <div class="item-info">
            <img class="product-image-history" :src=imageUrl alt="bag" />
            <div class="title-and-price-container">
                <p>{{ productName }} x{{ quantity }}</p>
                <p class="product-price">{{ price }} ({{ +price * +quantity }}) USD</p>
            </div>
        </div>
    </div>
</template>
