// angular/inexperienced/webshop/src/app/product-info/product-info.component.ts
import { Component, OnInit } from '@angular/core';
import ProductService from '../config/product.service';
import { ActivatedRoute } from '@angular/router';
import ProductInterface from 'src/types/ProductInterface';
import ReviewInterface from 'src/types/ReviewInterface';
import LoginService from '../config/login.service';
import UserInterface from 'src/types/UserInterface';
import { FormControl, FormGroup, Validators } from '@angular/forms';
import CartService from '../config/cart.service';

@Component({
  selector: 'app-product-info',
  templateUrl: './product-info.component.html',
  styleUrls: ['./product-info.component.css'],
})
export class ProductInfoComponent implements OnInit {
  id: string
  productById: ProductInterface;
  reviews: ReviewInterface[] = []

  reviewForm = new FormGroup({
    rating: new FormControl(0, [Validators.required, Validators.min(1), Validators.max(5)],),
    comment: new FormControl('', [Validators.required, Validators.minLength(10)])
  })

  user: UserInterface | null;

  constructor(
    private productService: ProductService,
    private cartService: CartService,
    private router: ActivatedRoute,
    private loginService: LoginService
  ) { }

  ngOnInit() {
    this.router.paramMap.subscribe((params) => {
      this.id = params.get('id') as string;

      this.productService.getProductById(this.id).subscribe(res => {
        this.productById = res;
      });

      this.fetchReviews()
    })

    this.loginService.user.subscribe(user => this.user = user)
  }

  fetchReviews() {
    this.productService.getProductReviews(this.id).subscribe(res => {
      this.reviews = res;
    });
  }

  addToCart() {
    this.cartService.addToCart(this.productById)
    alert('Added to cart! :)')
  }

  addReview() {
    if (!this.user) {
      alert('Please login to add a review')
      return
    }

    this.reviewForm.markAllAsTouched()

    if (this.reviewForm.invalid) {
      return alert('Invalid form!')
    }

    this.productService.addReview(
      this.id,
      this.reviewForm.value.rating!,
      this.reviewForm.value.comment!,
      this.user.token
    ).subscribe(() => this.fetchReviews())

    this.reviewForm.reset({
      rating: 0,
      comment: ''
    })
  }
}

<main>
    <div class="wrapper">
        <!-- Product Information -->
        <div class="product" *ngIf="productById !== undefined">
            <div class="product-image">
                <!-- svelte-ignore a11y-img-redundant-alt -->
                <img src={{productById.image_url}} alt="Product Image" />
            </div>

            <div class="product-info">
                <h3>{{productById.name}}</h3>
                <p>{{productById.short_description}}</p>

                <h2>{{productById.price}} USD</h2>
                <button class="product-item-buttons" (click)="addToCart()">Add to Cart</button>

                <h4>Description</h4>
                <p>
                    {{productById.long_description}}
                </p>
            </div>
        </div>

        <h1>Product Reviews</h1>

        <div class="reviews">
            <app-review *ngFor="let review of reviews" [comment]="review.comment" [rating]="review.rating"
                [rater]="review.rater" />
        </div>

        <p *ngIf="!reviews.length">This item has no reviews</p>

        <!-- Leave a review -->
        <h1>Leave a Review</h1>

        <form [formGroup]="reviewForm" *ngIf="user">
            <section class="user-input">
                <select class="input-stars" formControlName="rating">
                    <option [ngValue]="0">-- Please choose an option --</option>
                    <option [ngValue]="1">1 Star</option>
                    <option [ngValue]="2">2 Stars</option>
                    <option [ngValue]="3">3 Stars</option>
                    <option [ngValue]="4">4 Stars</option>
                    <option [ngValue]="5">5 Stars</option>
                </select>

                <div *ngIf="reviewForm.controls['rating'].invalid && (reviewForm.controls['rating'].dirty || reviewForm.controls['rating'].touched)"
                    class="alert alert-danger">
                    A rating must be selected, choose 1 for the lowest rating and 5 for the highest.
                </div>

                <textarea class="input-feedback" placeholder="Write what you think about the product"
                    formControlName="comment"></textarea>

                <div *ngIf="reviewForm.controls['comment'].invalid && (reviewForm.controls['comment'].dirty || reviewForm.controls['comment'].touched)"
                    class="alert alert-danger">
                    A comment must be entered and must be at least 10 characters long.
                </div>

                <button class="product-item-buttons" (click)="addReview()">Submit Review</button>
            </section>
        </form>

        <p *ngIf="!user" class="no-user">You must be logged in to leave a review</p>
    </div>
</main>

// svelte/inexperienced/webshop/src/components/product-info.svelte
<script lang="ts">
    import type ProductInterface from "../types/ProductInterface";
    import { cart } from "../stores/CartStore";
    import type { Review } from "../types/Review";
    import ReviewItem from "./review-item.svelte";
    import { activeUser } from "../stores/ActiveUserStore";
    import type { ActiveUser } from "../types/ActiveUser";
    import { field, form } from "svelte-forms";
    import { max, min, required } from "svelte-forms/validators";
    import { addReview, getReviews } from "../api/reviews";

    export let product: ProductInterface;
    export let reviews: Review[];

    let user: ActiveUser | undefined;
    activeUser.subscribe((value) => (user = value));

    const rating = field("rating", 0, [min(1), max(5)]);
    const comment = field("comment", "", [required(), min(10)]);

    const reviewForm = form(rating, comment);

    async function onSubmit() {
        if (user === undefined) {
            alert("You must be logged in to add a review");
            return;
        }

        await Promise.all([rating.validate(), comment.validate()]);

        if ($reviewForm.errors.length) {
            return alert("Invalid form! Please try again");
        }

        const response = await addReview(
            {
                rating: $rating.value,
                comment: $comment.value,
                rater: user.username,
                product_id: product._id,
            },
            user.accessToken
        );

        if (response.status_code >= 400) {
            return alert(`ERROR: ${response.detail}`);
        }

        reviews = await getReviews(product._id);
        reviewForm.reset();
        return alert("Comment added!");
    }
</script>

<!-- Product Information -->
<main>
    <div class="pi-product">
        <div class="pi-product-image">
            <!-- svelte-ignore a11y-img-redundant-alt -->
            <img
                src={product.image_url}
                alt="Product Image"
                class="pi-product-image"
            />
        </div>

        <div class="pi-product-info">
            <h3>{product.name}</h3>
            <p>{product.short_description}</p>

            <h2>{product.price} USD</h2>
            <button
                class="pi-product-item-buttons"
                on:click={() => {
                    cart.add(product);
                    alert("Added to cart!");
                }}>Add to Cart</button
            >

            <h4>Description</h4>
            <p>
                {product.long_description}
            </p>
        </div>
    </div>

    <!-- Reviews -->
    <h1>Product Reviews</h1>

    <div class="reviews">
        {#if !reviews.length}
            <p>No reviews yet</p>
        {/if}

        {#each reviews as review}
            <ReviewItem
                author={review.rater}
                comment={review.comment}
                rating={review.rating}
            />
        {/each}
    </div>

    <!-- Leave a review -->
    <h1>Leave a Review</h1>

    <section class="user-input">
        <select class="input-stars" bind:value={$rating.value}>
            <option value={0}>-- Please choose an option --</option>
            <option value={1}>1 Star</option>
            <option value={2}>2 Stars</option>
            <option value={3}>3 Stars</option>
            <option value={4}>4 Stars</option>
            <option value={5}>5 Stars</option>
        </select>

        {#if $reviewForm.hasError("rating.min")}
            <p class="input-error">Must at least be 1 star</p>
        {/if}

        <textarea
            class="input-feedback"
            placeholder="Write what you think about the product"
            bind:value={$comment.value}
        />

        {#if $reviewForm.hasError("comment.required")}
            <p class="input-error">You must write a comment</p>
        {/if}

        {#if $reviewForm.hasError("comment.min")}
            <p class="input-error">
                Your comment must be at least 10 characters
            </p>
        {/if}

        <button class="pi-product-item-buttons" on:click={() => onSubmit()}
            >Submit Review</button
        >
    </section>
</main>

<style>
    .input-error {
        color: red;
        border: 1px solid red;
        padding: 8px;
        font-weight: bold;
        border-radius: 8px;
    }
</style>
