// solid/experienced/src/pages/frontpage/FrontPage.tsx
import { useNavigate } from "@solidjs/router";
import { Component, For, Show, createResource } from "solid-js";
import { getProducts } from "../../api/getProducts";
import HeroImage from "../../assets/bag_image_frontpage.png";
import ProductItem from "../../components/ProductItem";
import styles from "./FrontPage.module.css";

const FrontPage: Component = () => {
    const navigate = useNavigate();

    const [products] = createResource(async () => {
        return await getProducts(6);
    });

    return (
        <main class={styles.main}>
            <div class={styles["image-container"]}>
                <img
                    class={styles["image"]}
                    src={HeroImage}
                    alt="frontpage image"
                />
            </div>

            <div class={styles["product-info"]}>
                <h1>BRAND NEW PRODUCTS</h1>

                <p class={styles["product-title-description"]}>
                    A wide selection of products can be found on our webshop
                </p>
            </div>

            <Show when={products.loading}>
                <h1>Loading...</h1>
            </Show>

            <Show when={products.error}>
                <h1>Products could not be retrieved, try refreshing</h1>
            </Show>

            <Show when={products()?.length}>
                <div class={styles["product-container"]}>
                    <For each={products()}>
                        {(product) => <ProductItem product={product} />}
                    </For>
                </div>
            </Show>

            <button
                onClick={() => navigate("/products")}
                class={styles["view-all-btn"]}
            >
                View All Items
            </button>
        </main>
    );
};

export default FrontPage;

// angular/inexperienced/webshop/src/app/frontpage/frontpage.component.ts
import { Component, OnInit } from '@angular/core';
import ProductInterface from 'src/types/ProductInterface';
import ProductService from '../config/product.service';

@Component({ selector: 'app-frontpage', templateUrl: 'frontpage.component.html', styleUrls:[ 'frontpage.component.css'] })

export class FrontpageComponent implements OnInit {
    products: ProductInterface[] = []

    constructor(public productService: ProductService) { }

    ngOnInit() {      
        this.productService.getFrontpageProducts().subscribe(response => {
            this.products = response
        })
    }
}
<main>
    <div class="image-container">
        <img class="image" src="../../assets/bag_image_frontpage.png" alt="frontpage image" />
    </div>

    <div class="product-info">
        <h1>BRAND NEW PRODUCTS</h1>

        <p class="product-title-description">
            A wide selection of products can be found on our webshop
        </p>
    </div>

    <div class="product-container">

        <div class="product" *ngFor="let fp_product of products;">
            <img src={{fp_product.image_url}} alt="a randomly generated image" />
            <button routerLink="product/{{fp_product._id}}">View item</button>

            <p class="product-description">{{fp_product.name}}</p>
            <p class="product-price">{{fp_product.price}} USD</p>
        </div>

    </div>

    <button [routerLink]="['/all-products']" class="view-all-btn"> View All Items</button>
</main>
