// angular/inexperienced/webshop/src/app/login/login.component.ts
import { Component, OnInit } from "@angular/core";
import RegisterService from "../config/register.service";
import RegisterInterface from "src/types/RegisterInterface";
import { FormControl, FormGroup, Validators } from "@angular/forms";
import LoginInterface from "src/types/LoginInterface";
import LoginService from "../config/login.service";
import { Router } from "@angular/router";

@Component({
  selector: "app-login",
  templateUrl: "./login.component.html",
  styleUrls: ["./login.component.css"],
})
export class LoginComponent implements OnInit {
  loginForm: FormGroup;

  constructor(private loginService: LoginService, private router: Router) { }

  ngOnInit() {
    this.loginForm = new FormGroup({
      username: new FormControl("", [
        Validators.required,
        Validators.minLength(6),
      ]),
      password: new FormControl("", [
        Validators.required,
        Validators.minLength(8),
      ]),
    });
  }

  onSubmit() {
    if (this.loginForm.invalid) {
      return alert("Invalid form!");
    }

    this.loginService.login(this.loginForm.value).subscribe((response) => {
      if (response.status_code === 400) {
        this.loginService.user.next(null)
        return alert(response.detail)
      }

      this.loginService.user.next({
        username: this.loginForm.value.username,
        token: response.access_token as string,
      })

      this.router.navigate(["/"]);
      alert("You have successfully logged in!");
    });
  }
}

<form [formGroup]="loginForm" novalidate>
    <div class="container">
        <h2>LOGIN</h2>
        <p>Login to leave reviews and comments</p>
        <input formControlName="username" name="username" type="text" class="form-field" placeholder="Your name"
            required />
        <div *ngIf="loginForm.controls['username'].invalid && (loginForm.controls['username'].dirty || loginForm.controls['username'].touched)"
            class="alert alert-danger">
            Name is required and should be at minimum 6 characters.
        </div>

        <input formControlName="password" name="passowrd" type="password" class="form-field" placeholder="Your password"
            required />
        <div *ngIf="loginForm.controls['password'].invalid && (loginForm.controls['password'].dirty || loginForm.controls['password'].touched)"
            class="alert alert-danger">
            Password should be at minimum 8 characters long.
        </div>

        <button (click)="onSubmit()" class="login-button">Login</button>
    </div>
</form>

// svelte/inexperienced/webshop/src/routes/login/+page.svelte
<script lang="ts">
    import { login } from "../../api/login";
    import "../css/register.css";
    import { form, field } from "svelte-forms";
    import { required } from "svelte-forms/validators";
    import { min } from "svelte-forms/validators";
    import { activeUser } from "../../stores/ActiveUserStore";
    import type LoginForm from "../../types/LoginFormInterface";

    const username = field("username", "", [required(), min(5)]);
    const password = field("password", "", [required(), min(5)]);

    const loginForm = form(username, password);

    async function onSubmit() {
        await Promise.all([username.validate(), password.validate()]);

        if ($loginForm.errors.length) {
            return alert("Invalid form! Please try again");
        }

        const response = await login(loginForm.summary() as LoginForm);

        if (response.status_code === 400) {
            return alert(`ERROR: ${response.detail}`);
        }

        activeUser.set({
            username: $username.value,
            accessToken: response.access_token,
            refreshToken: response.refresh_token,
        });

        return alert("You have successfully logged in");
    }
</script>

<div class="container">
    <h2>Login</h2>
    <p>Login to leave reviews and comments</p>
    <input
        bind:value={$username.value}
        type="text"
        class="form-field"
        placeholder="Your name"
    />

    {#if $loginForm.hasError("username.required")}
        <div class="error">Username is required</div>
    {/if}

    {#if $loginForm.hasError("username.min")}
        <div class="error">Username must be at least 5 characters</div>
    {/if}

    <input
        bind:value={$password.value}
        type="text"
        class="form-field"
        placeholder="Your password"
    />

    {#if $loginForm.hasError("password.required")}
        <div class="error">Password is required</div>
    {/if}

    {#if $loginForm.hasError("password.required")}
        <div class="error">Password must be at least 5 characters</div>
    {/if}

    <button on:click={() => onSubmit()} class="login-button">Login</button>
</div>

<style>
    input {
        outline: none;
    }

    :global(.invalid),
    :global(.error) {
        border: 1px solid red;
    }

    :global(.valid),
    :global(.foo) {
        border: 1px solid green;
    }

    :global(.dirty) {
        border: 1px dashed black;
    }
</style>
