// vue/experienced/src/components/HistoryOrderItem.vue

<script lang="ts">

export default {
    props: {
        imageUrl: String,
        productName: String,
        price: Number,
        quantity: Number
    }
}
</script>

<template>
    <div class="item-container">
        <div class="item-info">
            <img class="product-image-history" :src=imageUrl alt="bag" />
            <div class="title-and-price-container">
                <p>{{ productName }} x{{ quantity }}</p>
                <p class="product-price">{{ price }} ({{ +price * +quantity }}) USD</p>
            </div>
        </div>
    </div>
</template>

// angular/inexperienced/webshop/src/app/history-order/history-order-item/history-order-item.component.ts
import { Component, Input } from "@angular/core";

@Component({
  selector: "app-history-order-item",
  templateUrl: "./history-order-item.component.html",
  styleUrls: ["./history-order-item.component.css"],
})
export class HistoryOrderItemComponent {

  @Input() id: string;
  @Input() quantity: Date
  @Input() price: number;
  @Input() image_url: string;
}

<div class="item-container">
    <div class="item-info">
        <img class="product-image" src="guccibag.png" alt="bag" />
        <div class="title-and-price-container">
            <p>The classic bag x2</p>
            <p class="product-price">799 USD</p>
        </div>
    </div>
</div>
